Q6: API pods allow frontend pods + external IP

Question:
In namespace sales, pods labeled app: api should allow traffic from:

a) Pods labeled app: web in same namespace
b) External IPs (internet) on port 443 All other traffic blocked.

#ans
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-web-and-internet
  namespace: sales
spec:
  podSelector:
    matchLabels:
      app: api
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: web
  - from:
    - ipBlock:
        cidr: 0.0.0.0/0
    ports:
    - protocol: TCP
      port: 443
