Q9: Grafana pods allow Prometheus + external IP

Question:
Namespace monitoring, pods labeled app: grafana should allow traffic from:
  a) Pods labeled app: prometheus (same namespace)
  b) External IP range 192.168.0.0/16 & Only on port 3000.

#Ans
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-prometheus-and-ip
  namespace: monitoring
spec:
  podSelector:
    matchLabels:
      app: grafana
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: prometheus
    ports:
    - protocol: TCP
      port: 3000
  - from:
    - ipBlock:
        cidr: 192.168.0.0/16
    ports:
    - protocol: TCP
      port: 3000
